---
# file: environments/dev/hosts.yml

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_host: localhost
    corellia:
      ansible_host:
    dantooine:
      ansible_host:
    hoth:
      ansible_host:
    yavin:
      ansible_host:
  vars:
    ansible_become_password:
    ansible_connection: ssh
    ansible_user:
    libvirt_connection: "qemu:///system"
  children:
    cloud:
      hosts:
        hoth:
        yavin:
    libvirtd:
      hosts:
        localhost:
        dantooine:
    vms:
      hosts:
        corellia:
        dantooine:
        hoth:
        yavin:
